package com.joca.frontend;

import com.joca.frontend.forms.EventForm;
import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;

/**
 *
 * @author joca
 */
public class FramePrincipal extends javax.swing.JFrame {

    private LogPrinter logPrinter;

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        logPrinter = new LogPrinter();
        panePrincipal.add(logPrinter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panePrincipal = new javax.swing.JDesktopPane();
        optionsMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadFileMenu = new javax.swing.JMenuItem();
        actionsMenu = new javax.swing.JMenu();
        eventsMenu = new javax.swing.JMenuItem();
        participantsMenu = new javax.swing.JMenuItem();
        registrationsMenu = new javax.swing.JMenu();
        registrationsMenuItem = new javax.swing.JMenuItem();
        paymentMenu = new javax.swing.JMenuItem();
        validationsMenu = new javax.swing.JMenuItem();
        activitiesMenu = new javax.swing.JMenuItem();
        attendanceMenu = new javax.swing.JMenuItem();
        logMenu = new javax.swing.JMenu();
        consoleMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panePrincipalLayout = new javax.swing.GroupLayout(panePrincipal);
        panePrincipal.setLayout(panePrincipalLayout);
        panePrincipalLayout.setHorizontalGroup(
            panePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panePrincipalLayout.setVerticalGroup(
            panePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        fileMenu.setText("Archivo");

        loadFileMenu.setText("Cargar archivo");
        loadFileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileMenuActionPerformed(evt);
            }
        });
        fileMenu.add(loadFileMenu);

        optionsMenu.add(fileMenu);

        actionsMenu.setText("Acciones");

        eventsMenu.setText("Eventos");
        eventsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsMenuActionPerformed(evt);
            }
        });
        actionsMenu.add(eventsMenu);

        participantsMenu.setText("Participantes");
        participantsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantsMenuActionPerformed(evt);
            }
        });
        actionsMenu.add(participantsMenu);

        registrationsMenu.setText("Inscripciones");

        registrationsMenuItem.setText("Inscripciones");
        registrationsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationsMenuItemActionPerformed(evt);
            }
        });
        registrationsMenu.add(registrationsMenuItem);

        paymentMenu.setText("Pagos");
        paymentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentMenuActionPerformed(evt);
            }
        });
        registrationsMenu.add(paymentMenu);

        validationsMenu.setText("Validaciones");
        validationsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validationsMenuActionPerformed(evt);
            }
        });
        registrationsMenu.add(validationsMenu);

        actionsMenu.add(registrationsMenu);

        activitiesMenu.setText("Actividades");
        activitiesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activitiesMenuActionPerformed(evt);
            }
        });
        actionsMenu.add(activitiesMenu);

        attendanceMenu.setText("Asistencia");
        attendanceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceMenuActionPerformed(evt);
            }
        });
        actionsMenu.add(attendanceMenu);

        optionsMenu.add(actionsMenu);

        logMenu.setText("Consola");

        consoleMenu.setText("Abrir consola");
        consoleMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleMenuActionPerformed(evt);
            }
        });
        logMenu.add(consoleMenu);

        optionsMenu.add(logMenu);

        setJMenuBar(optionsMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void openNewWindow(JInternalFrame internalFrame) {
        internalFrame.setLocation(
                (int) (Math.random() * 200),
                (int) (Math.random() * 200)
        );
        internalFrame.setVisible(true);

        panePrincipal.add(internalFrame);
        try {
            internalFrame.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }

    private void loadFileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadFileMenuActionPerformed

    private void eventsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsMenuActionPerformed
        EventForm eventForm = new EventForm(this);
        openNewWindow(eventForm);
    }//GEN-LAST:event_eventsMenuActionPerformed

    private void participantsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantsMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participantsMenuActionPerformed

    private void activitiesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activitiesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activitiesMenuActionPerformed

    private void attendanceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendanceMenuActionPerformed

    private void registrationsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationsMenuItemActionPerformed

    private void paymentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentMenuActionPerformed

    private void validationsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validationsMenuActionPerformed
        
    }//GEN-LAST:event_validationsMenuActionPerformed

    private void consoleMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleMenuActionPerformed
        if (logPrinter.isIcon()) {
            try {
                logPrinter.setIcon(false);
            } catch (PropertyVetoException ex) {
                ex.printStackTrace();
            }
        }
        logPrinter.setVisible(true);
    }//GEN-LAST:event_consoleMenuActionPerformed

    public void printOnLog(String message) {
        logPrinter.insertLine(message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actionsMenu;
    private javax.swing.JMenuItem activitiesMenu;
    private javax.swing.JMenuItem attendanceMenu;
    private javax.swing.JMenuItem consoleMenu;
    private javax.swing.JMenuItem eventsMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem loadFileMenu;
    private javax.swing.JMenu logMenu;
    private javax.swing.JMenuBar optionsMenu;
    private javax.swing.JDesktopPane panePrincipal;
    private javax.swing.JMenuItem participantsMenu;
    private javax.swing.JMenuItem paymentMenu;
    private javax.swing.JMenu registrationsMenu;
    private javax.swing.JMenuItem registrationsMenuItem;
    private javax.swing.JMenuItem validationsMenu;
    // End of variables declaration//GEN-END:variables
}
