/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.joca.frontend;

/**
 *
 * @author joca
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panePrincipal = new javax.swing.JDesktopPane();
        optionsMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadFileMenu = new javax.swing.JMenuItem();
        actionsMenu = new javax.swing.JMenu();
        eventsMenu = new javax.swing.JMenuItem();
        participantsMenu = new javax.swing.JMenuItem();
        registrationsMenu = new javax.swing.JMenu();
        registrationsMenuItem = new javax.swing.JMenuItem();
        paymentMenu = new javax.swing.JMenuItem();
        validationsMenu = new javax.swing.JMenuItem();
        activitiesMenu = new javax.swing.JMenuItem();
        attendanceMenu = new javax.swing.JMenuItem();
        logMenu = new javax.swing.JMenu();
        consoleMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panePrincipalLayout = new javax.swing.GroupLayout(panePrincipal);
        panePrincipal.setLayout(panePrincipalLayout);
        panePrincipalLayout.setHorizontalGroup(
            panePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        panePrincipalLayout.setVerticalGroup(
            panePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        fileMenu.setText("Archivo");

        loadFileMenu.setText("Cargar archivo");
        loadFileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileMenuActionPerformed(evt);
            }
        });
        fileMenu.add(loadFileMenu);

        optionsMenu.add(fileMenu);

        actionsMenu.setText("Acciones");

        eventsMenu.setText("Eventos");
        eventsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsMenuActionPerformed(evt);
            }
        });
        actionsMenu.add(eventsMenu);

        participantsMenu.setText("Participantes");
        participantsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantsMenuActionPerformed(evt);
            }
        });
        actionsMenu.add(participantsMenu);

        registrationsMenu.setText("Inscripciones");

        registrationsMenuItem.setText("Inscripciones");
        registrationsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationsMenuItemActionPerformed(evt);
            }
        });
        registrationsMenu.add(registrationsMenuItem);

        paymentMenu.setText("Pagos");
        paymentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentMenuActionPerformed(evt);
            }
        });
        registrationsMenu.add(paymentMenu);

        validationsMenu.setText("Validaciones");
        validationsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validationsMenuActionPerformed(evt);
            }
        });
        registrationsMenu.add(validationsMenu);

        actionsMenu.add(registrationsMenu);

        activitiesMenu.setText("Actividades");
        activitiesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activitiesMenuActionPerformed(evt);
            }
        });
        actionsMenu.add(activitiesMenu);

        attendanceMenu.setText("Asistencia");
        attendanceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceMenuActionPerformed(evt);
            }
        });
        actionsMenu.add(attendanceMenu);

        optionsMenu.add(actionsMenu);

        logMenu.setText("Consola");

        consoleMenu.setText("Abrir consola");
        consoleMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleMenuActionPerformed(evt);
            }
        });
        logMenu.add(consoleMenu);

        optionsMenu.add(logMenu);

        setJMenuBar(optionsMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadFileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadFileMenuActionPerformed

    private void eventsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventsMenuActionPerformed

    private void participantsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantsMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participantsMenuActionPerformed

    private void activitiesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activitiesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activitiesMenuActionPerformed

    private void attendanceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendanceMenuActionPerformed

    private void registrationsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationsMenuItemActionPerformed

    private void paymentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentMenuActionPerformed

    private void validationsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validationsMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validationsMenuActionPerformed

    private void consoleMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleMenuActionPerformed
        System.out.println("sss");
    }//GEN-LAST:event_consoleMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actionsMenu;
    private javax.swing.JMenuItem activitiesMenu;
    private javax.swing.JMenuItem attendanceMenu;
    private javax.swing.JMenuItem consoleMenu;
    private javax.swing.JMenuItem eventsMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem loadFileMenu;
    private javax.swing.JMenu logMenu;
    private javax.swing.JMenuBar optionsMenu;
    private javax.swing.JDesktopPane panePrincipal;
    private javax.swing.JMenuItem participantsMenu;
    private javax.swing.JMenuItem paymentMenu;
    private javax.swing.JMenu registrationsMenu;
    private javax.swing.JMenuItem registrationsMenuItem;
    private javax.swing.JMenuItem validationsMenu;
    // End of variables declaration//GEN-END:variables
}
