/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.joca.frontend;

import com.joca.model.DBEntity;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joca
 */
public class GenericTable extends javax.swing.JInternalFrame {

    private DefaultTableModel model;

    public static final String[] EVENT_MODEL = {"Código", "Titulo", "Ubicación", "Tipo", "Fecha", "Capacidad", "Precio"};
    public static final String[] PARTICIPANT_MODEL = {"Email", "Nombre", "Tipo", "Institución"};
    public static final String[] REGISTRATION_MODEL = {"Evento", "Email participante", "Tipo", "Método de pago", "Monto", "Estado"};

    /**
     * Creates new form LogPrinter
     */
    public GenericTable(List<DBEntity> entities, String[] MODEL, String title) {
        initComponents();
        setTitle(title);
        model = new DefaultTableModel(MODEL, 0);
        table.setModel(model);
        table.setDefaultEditor(Object.class, null);
        insertRows(entities);
    }

    private void insertRows(List<DBEntity> entities) {
        for (DBEntity entity : entities) {
            model.addRow(entity.getAsRow());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Log");

        jScrollPane1.setBorder(null);
        jScrollPane1.setAutoscrolls(true);

        table.setAutoCreateRowSorter(true);
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setSelectionBackground(new java.awt.Color(204, 204, 204));
        table.setSelectionForeground(new java.awt.Color(51, 51, 51));
        table.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
