/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.joca.frontend;

import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joca
 */
public class LogPrinter extends javax.swing.JInternalFrame {

    private DefaultTableModel model;
    /**
     * Creates new form LogPrinter
     */
    public LogPrinter() {
        initComponents();
        model = new DefaultTableModel(new String[]{"Historial de operaciones"}, 0);
        canvas.setModel(model);
        canvas.setDefaultEditor(Object.class, null);
    }
    
    public void insertLine(String mensaje){
        String linea = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss")) + " => " + mensaje;
        model.addRow(new String[] {linea});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        canvas = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Log");

        jScrollPane1.setBorder(null);
        jScrollPane1.setAutoscrolls(true);

        canvas.setBackground(new java.awt.Color(102, 102, 102));
        canvas.setForeground(new java.awt.Color(255, 255, 255));
        canvas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        canvas.setGridColor(new java.awt.Color(102, 102, 102));
        canvas.setOpaque(false);
        canvas.setSelectionBackground(new java.awt.Color(51, 51, 51));
        canvas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(canvas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable canvas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
